name: Build README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: build
        run: cat README.template.md | sed "s/%randomNumber%/$(shuf -i 0-100 -n 1)/" > README.md

      - name: commit and push
        run: |-
          git config --global user.email "readme@example.com"
          git config --global user.name "README.md auto updater"
          git add --all
          git commit -m "Update README.md" || exit 0
          git push
