name: Build README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: build
        run: |
          echo "# Hey there 👋

          I don’t really know what to add here, so here is the random number that will be updated once an hour: **$(shuf -i 0-100 -n 1)**" > README.md

      - name: commit and push
        run: |-
          git config --global user.email "readme@example.com"
          git config --global user.name "README.md auto updater"
          git add --all
          git commit -m "Update README.md" || exit 0
          git push
