name: Build README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: build
        run: sh build.sh

      - name: commit and push
        run: |-
          git config --global user.email "readme@example.com"
          git config --global user.name "README.md auto updater"
          git add --all
          git commit -m "Update README.md" || exit 0
          git push
