name: Generate README

on:
  schedule:
    - cron: "16 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: build
        with:
          node-version: "12.x"
        run: npm start

      - name: push
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: "master"
          commit-message: "Update README.md"
          force-add: "true"
          files: README.md
          name: GitHub Action
          email: github-action@example.com
